### ISSUE TITLE
[feature] Color improvement

### ISSUE THREAD

**Issue by bvandergiessen** [syncfiddle/syncfiddle-issues#9]
For color-blind people, the text of some items is almost unreadable against the black background. I'm talking about

1. unrecognized keywords – this CSS rule:

```css
.cm-s-ambiance .cm-error {
	color:#af2018
}
```

2. comments – this rule:

```css
.cm-s-ambiance .cm-comment {
	color:#555;
	font-style:italic
}
```

Could the colors be changed for 'accessibility'? The developer tools of some browsers (at least Firefox) make this easy: click the color in the CSS inspector and it shows an accessibility score for that color against that background.
